Improve gradient test
asturur/node-canvas pull request #1
Opened 2019-06-06 02:24 UTC by NightYoshi370

Thanks for contributing!

- [ ] Have you updated CHANGELOG.md?

2019-06-06 06:38 UTC, asturur requested changes

2019-06-06 06:38 UTC, asturur commented on test/public/tests.js
> +    ctx.rotate(0 + i * 2, 0, 1)
this is the rotate function, is not ctx.rotate

2019-06-07 00:34 UTC, NightYoshi370 commented
Fixed the change you requested

2019-06-07 09:22 UTC, asturur approved these changes

2019-06-07 09:22 UTC, merged